name: BuildersWand
main: io.github.bananapuncher714.builderswand.BuildersWand
version: 1.1
description: Builders wand in Minecraft
author: BananaPuncher714
commands:
  builderswand:
    aliases: []
permissions:
  builderswand.use:
    default: true
  builderswand.admin:
    default: op