name: BuildersWand
main: network.aeternum.builderswand.BuildersWand
version: 1.2
description: Builders wand in Minecraft
author: BananaPuncher714
commands:
  builderswand:
    aliases: []
permissions:
  builderswand.use:
    default: true
  builderswand.admin:
    default: op